### ISSUE TITLE
API for Whisper?

### ISSUE THREAD

**Issue by lunaroyster** [julep-ai/julep#382]
It would be nice if the julep client would have an abstraction for working with openai whisper. 

Some ideas:
- people want transcriptions of different types: 
  - sometimes, you want them word-to-word accurate, for uses like video subtitles. you also want to group them up by time (maybe literally return an .srt file for a video)
  - sometimes, you want them for written content: here you absolutely need some post-processing to make sure that the text is correctly formatted and readable, instead of a literal transcription
  - sometimes you just want a summary, or you want to answer a question
- transcription is expensive: you can cache transcriptions / post-processed outputs for users

An abstraction over whisper would use completions in conjunction with the whisper transcript to return more suitable transcriptions

**Comment by creatorrr** [comment]
Yep, makes sense. We could def do this over the streaming responses. And possibly even for text-to-speech as well.

(Btw, we are running a bounty program so happy to add this issue to it if you want to take it up.)
