### ISSUE TITLE
feat(agents-api): Allow developers to optionally specify and set the UUID when creating (agent, session, user) objects through the REST API

### ISSUE THREAD

**Issue by creatorrr** [julep-ai/julep#392]
Need to change the following code:
- `openapi.yaml`: allow `id` parameter as optional uuid string in POST /agents, /users, /sessions

And check if `id` parameter was passed in the POST handler, if not, then generate a new one:
- `agents-api/agents_api/routers/agents/routers.py`
- `agents-api/agents_api/routers/users/routers.py`
- `agents-api/agents_api/routers/sessions/routers.py`

**Comment by KunjShah95** [comment]
Can u assign it to me

**Comment by creatorrr** [comment]
Closing as previously completed
