### ISSUE TITLE
bug: `client.sessions.history()` doesn't display the system prompts with `situation` and `instructions`

### ISSUE THREAD

**Issue by alt-glitch** [julep-ai/julep#398]
As title says.

`client.sessions.history()` only returns the `user` and `assistant` turns of the conversations and not the initial system prompt.

**Comment by KunjShah95** [comment]
Possible Issues and Solutions
1)System Prompts Not Being Stored Correctly
Issue:
System prompts (e.g., messages with the role system) might not be saved to the session history.
Solution:
Ensure that when system prompts are sent, they are correctly added to the session history. Verify that the saving mechanism includes all message types.
  function saveMessage(message) {
       // Ensure all message roles are saved, including 'system'
       session.history.push(message);
       // Existing save logic...
   }
2)history() Method Filters Out System Messages
Issue:
The history() method may be inadvertently filtering out messages with the role system.
Solution:
Review the history() method to confirm it retrieves all message types. Modify it to include system messages if it filters them out.
def history(self):
       # Ensure system messages are included
       return [msg for msg in self.session_history if msg['role'] in ['user', 'assistant', 'system']]
3)Incorrect Role Assignment for System Prompts
Issue:
System prompts might not be correctly labeled with the system role, causing them to be excluded from the history.
Solution:
Check that all system prompts are assigned the correct role when created.
def create_system_prompt(content):
       return {
           "role": "system",
           "content": content
       }
4) Asynchronous Saving Issues
Issue:
If message saving is asynchronous, system prompts might not be saved before history() is called.
Solution:
Ensure that all messages, especially system prompts, are fully saved before retrieving the history.
async function saveMessageAsync(message) {
       await database.save(message);
       session.history.push(message);
   }

   async function getHistory() {
       await ensureAllMessagesSaved();
       return client.sessions.history();
   }
5.Database Query Limitations
Issue:
The underlying database query for history retrieval might exclude certain message types.
Solution:
Inspect and modify the database queries to include system prompts.
SELECT * FROM messages
   WHERE session_id = :session_id
   ORDER BY timestamp ASC;
Ensure that there are no WHERE clauses excluding system roles.
6)UI Rendering Issues
Issue:
Even if system messages are correctly retrieved, the frontend/UI might not render them.
Solution:
Verify that the frontend code iterates over all message types and displays them appropriately.
function SessionHistory({ history }) {
       return (
           <div>
               {history.map((msg, index) => (
                   <Message key={index} role={msg.role} content={msg.content} />
               ))}
           </div>
       );
   }
7)Access Permissions or Filters
Issue:
There might be permission settings or filters that prevent system messages from being accessed or displayed.
Solution:
Review access controls and ensure that system messages are accessible to the components or users that need them.
def can_view_system_messages(user):
       # Ensure users have the right permissions
       return user.has_permission('view_system_messages')
Summary
The primary reasons client.sessions.history() might not display system prompts are:
Storage Issues: System prompts aren't being saved correctly.
Filtering Problems: The history() method excludes system messages.
Role Misassignments: System prompts aren't labeled with the correct role.
Asynchronous Handling: Messages aren't saved before retrieval.
Database Constraints: Queries exclude system messages.
UI Limitations: Frontend doesn't render system messages.
Review each of these areas in your code to identify and resolve the issue. If you provide specific code snippets, I can offer more targeted assistance.

**Comment by KunjShah95** [comment]
KINDLY check above solution if it helps you

**Comment by creatorrr** [comment]
This has been fixed. Thanks @KunjShah95 :)

**Comment by KunjShah95** [comment]
WELCOME
