### ISSUE TITLE
[Good First Issue] Automate building and pushing postman collection

### ISSUE THREAD

**Issue by creatorrr** [julep-ai/julep#411]
maybe using this:
https://learning.postman.com/docs/integrations/intro-integrations/

prelim work already done

- [ ] complete github actions integration
- [ ] test sync
- [ ] update docs link

**Comment by itsamziii** [comment]
Hi, I would like to take this up once I'm sure what exactly will be done here. Is it perhaps [this](https://learning.postman.com/docs/integrations/available-integrations/ci-integrations/github-actions/) that needs to be implemented?
