### ISSUE TITLE
Make doc search configurable

### ISSUE THREAD

**Issue by creatorrr** [julep-ai/julep#418]

**Comment by Mayank77maruti** [comment]
Hey @creatorrr ,I would like to take on this issue. Please assign this issue to me so I can start working on it!

**Comment by creatorrr** [comment]
Happy to. Can you look into [cozo docs](https://docs.cozodb.org/en/latest/tutorial.html)? It's a bit of a learning curve but once you get the hang of it, it should be easy to contribute to this issue?
