### ISSUE TITLE
Making the navbar sticky

### ISSUE THREAD

**Issue by YadlaMani** [julep-ai/julep#541]
![image](https://github.com/user-attachments/assets/20ecee81-0b71-457b-8d8b-aecadbdf39e5)
Currently, the navbar scrolls up with the page, unlike other websites where it remains sticky. I would like to address this issue.

**Comment by prathamesh424** [comment]
can assign this issue to me

**Comment by anshuman-rai-27** [comment]
i am very comfortable with tech stack used in this project , can quickly make navbar sticky 
can you assign this issue to me ?

**Comment by kalyanshnu** [comment]
can i do this as this is something which was taught me in my class yesterday

**Comment by ijindal1** [comment]
Thanks for reporting, but this is built in Framer and we are updating the website.
