### ISSUE TITLE
[Good First Issue] Test and Provide Feedback on Contributor Setup Process

### ISSUE THREAD

**Issue by creatorrr** [julep-ai/julep#554]
👋 Welcome, new contributor! We need your help to improve our setup process.

🎯 **Objective**:
Follow the setup instructions in our CONTRIBUTING.md file and provide feedback on your experience. This will help us make the onboarding process smoother for future contributors.

🔧 **Tasks**:
1. Read through the CONTRIBUTING.md file.
2. Follow the setup instructions step by step.
3. Start all the required services.
4. Try making a small change (e.g., update a comment or add a console.log statement).
5. Provide feedback on your experience:
   - What went smoothly?
   - Did you encounter any issues or confusion?
   - Are there any steps that could be clearer?
   - Did you successfully make and test a change?

📝 **How to submit your feedback**:
- If you find specific issues or have suggestions for improvements, please create new issues for each one.
- For general feedback or if everything worked perfectly, please comment on this issue with your experience.

> 💡 Tip: Don't worry if you run into problems! Identifying issues is just as valuable as confirming that everything works.

Thank you for helping us improve Julep! Your input is crucial in making our project more accessible to new contributors. 🙌

**Comment by PRIYANKjakharia** [comment]
i can work on this

**Comment by creatorrr** [comment]
@PRIYANKjakharia can you also review https://github.com/julep-ai/julep/pull/556 pull request?

**Comment by PRIYANKjakharia** [comment]
> @PRIYANKjakharia can you also review #556 pull request?

yeah seems good to go

**Comment by Maulik-darji** [comment]
how many people are working on the following issue ?

**Comment by ijindal1** [comment]
Hi @Maulik-darji - can assign this to you if you want to work further on this.
