### ISSUE TITLE
BUG: Wrong redirection to docs in the footer

### ISSUE THREAD

**Issue by Ananya54321** [julep-ai/julep#577]
Description:
In the footer of the julep.ai website, when you click on docs, it redirects you to the wrong url for the readme of the docs. (It says page not found).

How To Reproduce the issue:
Go to the footer and click on docs

Expected Behaviour: 
To be redirected to https://docs.julep.ai/

Actual Behaviour:
It redirects to https://docs.julep.ai/introduction/readme

Screenshots:

<img width="1470" alt="Screenshot 2024-10-03 at 5 39 10 PM" src="https://github.com/user-attachments/assets/9e6398a0-6afb-43dd-86ac-eb3d466e0bb5">

**Comment by Ananya54321** [comment]
I would like to work on this issue. Can you please assign it to me under hacktoberfest and devfest?

**Comment by creatorrr** [comment]
The website is in framer so we can't do this on github but thanks for the report!
