### ISSUE TITLE
[Good First Issue] Add a github action that automatically translates the README into chinese, japanese, and french languages

### ISSUE THREAD

**Issue by creatorrr** [julep-ai/julep#600]
# Add a GitHub Action for Automatic README Translation

We'd like to make our project more accessible to non-English speakers by automatically translating our README into Chinese, Japanese, and French. This task involves setting up a GitHub Action to handle the translation process whenever the main README is updated.

## Objective

Create a GitHub Action workflow that:
1. Detects changes to the main `README.md` file
2. Translates the content into Chinese, Japanese, and French
3. Updates (or creates if they don't exist) the corresponding `README-CN.md`, `README-JP.md`, and `README-FR.md` files

## Implementation Suggestions

1. Configure the workflow to trigger on changes to `README.md`
4. Implement the translation logic using a script (Python, Node.js, or shell script)
5. Commit and push the translated files back to the repository

## Definition of Done

- GitHub Action workflow is created and functional
- README is automatically translated into Chinese, Japanese, and French when updated
- Translated files are correctly named and placed in the repository
- Action runs successfully on test commits

This is a great opportunity to learn about GitHub Actions and work with translation APIs. If you have any questions or need further clarification, please don't hesitate to ask in the comments!

**Comment by PavlisinPhoto** [comment]
Hi, I am new here and I would like to contribute on your project. This issue looks like great beginning. Can you assign me this issue?

**Comment by prathamesh424** [comment]
@creatorrr  can assign this issue to me

**Comment by AMANCHAUBEY8822** [comment]
i like to contribute your project so assign me

**Comment by creatorrr** [comment]
Please create a draft pull request for this if you're interested. If it looks good, happy to assign it :)

**Comment by itsamziii** [comment]
Hi, perhaps you could share the current manual method of converting the README files as from what I can understand there are many things to be looked out for the gh action, just want to all the basics ^^

**Comment by Ayushjhawar8** [comment]
i think we will need a translation api key for it to work. idk any free ones out there

**Comment by itsamziii** [comment]
Indeed that's one thing but the way Readme is designed it's tiresome to be able to separate out text that needs to be translated without losing the semantic meaning of the same. Of course using machine translation would be the best way to approach this but I think it'd be doable with just normal translation given there is a room for error and bad translations ^^

**Comment by d-beloved** [comment]
> Please create a draft pull request for this if you're interested. If it looks good, happy to assign it :)

Hello @creatorrr, when you mentioned draft pull request, what will constitute an acceptable draft PR. All the work, or hightlights of what will be done?
