### ISSUE TITLE
Add README-FR.md file

### ISSUE THREAD

**Issue by valay30** [julep-ai/julep#606]
Add a README-FR.md to Translation make our project more accessible to non-English speakers.

# Objective:
Add a French translation of the README file (README-FR.md) to make the project more accessible to French-speaking users and contributors, improving overall inclusivity and expanding the project's global reach.

# Implementation Suggestions:

**Create README-FR.md:**

- Start by creating a new file named README-FR.md in the root directory of the repository.
- Translate the content of the original README.md into French, ensuring clarity and accuracy in the translation.

**Consistency with English Version:**
- Ensure the French translation mirrors the structure, headings, and sections of the English README to maintain consistency across both documents.
- Keep technical terms like code snippets, commands, and file names in English where necessary, as these are often standard across languages.

**Add Language Switcher Links:**
- At the top of both README.md and README-FR.md, add links to switch between languages.

**Comment by Jeevan2305** [comment]
Assign me #606

**Comment by creatorrr** [comment]
It's assigned to @valay30 but actually we'd like to automate these translations. Closing in favor of #600
