### ISSUE TITLE
bug: Fix deploy/simple-docker-compose.yaml file

### ISSUE THREAD

**Issue by creatorrr** [julep-ai/julep#643]

**Comment by HarshitVashisht11** [comment]
Hi can you please specify what need to be fixed in `deploy/simple-docker-compose.yaml`

**Comment by creatorrr** [comment]
Does not work at the moment. Steps to reproduce:
1. `cp .env.example .env`
2. Edit `.env` file and set secrets
3. Try to run `docker compose up -d deploy/simple-docker-compose.yaml`

The error logs will show the broken service config.

**Comment by NikhilKalloli** [comment]
Hey @creatorrr, I can work on this issue. Can you please assign this to me.

**Comment by shanvijha30** [comment]
Hi @creatorrr I would like to work on this issue could you please assign me this issue.
