### ISSUE TITLE
[Feature]: Use gunicorn + uvicorn + uvloop on agents-api, worker, integrations (all python services)

### ISSUE THREAD

**Issue by creatorrr** [julep-ai/julep#728]
### 🔖 Feature description

We need to use multiple workers since we do have a fair bit of blocking code.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by HamadaSalhab** [comment]
Added for `agents-api`, will add them to the other services too.
