### ISSUE TITLE
[Feature]: Add a github stats on the header.

### ISSUE THREAD

**Issue by thakurboy004** [julep-ai/julep#738]
### 🔖 Feature description

It would be a great addition to the website to display GitHub stats, such as stars ⭐ and forks 🍴, which will help strengthen the integrity of the project and attract more contributors. Showcasing these stats can highlight the project's popularity and engagement, encouraging more users to get involved.

### ✌️ How do you aim to achieve this?

**Pull Request Proposal:**  
I propose adding GitHub statistics (stars and forks) to the website's header or footer, whichever is preferred. This feature will use dynamic badges to display real-time stats, enhancing user engagement by showcasing the project's popularity and contributions.

By adding these stats to the header or footer, users can easily track the number of stars ⭐ and forks 🍴 the project has received, making the website more informative and visually engaging.

If this proposal is accepted, I am happy to open a pull request to implement this feature.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by HamadaSalhab** [comment]
Thanks for suggesting this! We've already added that to the website, it's just hasn't been deployed yet.
