### ISSUE TITLE
[Feature] Add ragbench to the agents-api tests

### ISSUE THREAD

**Issue by creatorrr** [julep-ai/julep#743]
### 🔖 Feature description

- [x] Add a small split of the ragbench tests to our huggingface along with embedding, instruction and model columns @HamadaSalhab 
- [ ] Write tests in agents-api using the dataset for all three search types (as simple as possible) @whiterabbit1983 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by HamadaSalhab** [comment]
I have sampled 50 rows of the [ragbench](https://huggingface.co/datasets/rungalileo/ragbench), and added the following new columns:

- `question_embeddings`: The embeddings for the `question` column (2d array with shape (1,1024).
- `documents_embeddings`: The embeddings for the `documents` column (2d array with shape (4, 1024)).
- `question_embed_instruction`: The embed instruction used for embedding the question (equal to `"Represent the query for retrieving supporting documents: "` for all rows).
- `document_embed_instruction`: The embed instruction used for embedding the documents (equal to `Represent the document for retrieval: ` for all rows).
- `embedding_model`: The model used for embedding (equal to `voyage/voyage-3` for all rows).

 You can find the dataset [here](https://huggingface.co/datasets/julep-ai/ragbench-sampled-julep) (private within [julep-ai](https://huggingface.co/julep-ai) organization).

@whiterabbit1983 Let me know if you have any questions / find any problems.
