### ISSUE TITLE
[Bug]: `metadata_filter` Not Supported in SDKs

### ISSUE THREAD

**Issue by HamadaSalhab** [julep-ai/julep#807]
### 📜 Description

Reproduce:

```python
client.users.list(metadata_filter={'filter_key': 'filter_value'})
```

Error:

`TypeError: UsersResource.list() got an unexpected keyword argument 'metadata_filter'`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

**Comment by HamadaSalhab** [comment]
@whiterabbit1983 The error is gone (it's accepting a `metadata_filter` parameter). However, it's not working correctly. Running the following code is giving an empty list.

```py
client.users.create(name="new_user", metadata={"ppid": "123"})
client.users.list(metadata_filter={"ppid": "123"})
```

I can confirm it's not an issue from the endpoint `metadata_filter`. Doing the same thing in `Tasks` with a `system` tool gives the desired result.

**Comment by creatorrr** [comment]
`client.agents.list(metadata_filter={...})` also works correctly
![image](https://github.com/user-attachments/assets/1c649a9b-b6cb-4d3f-abf4-193663739121)

**Comment by creatorrr** [comment]
Figured out the problem... Because we are parsing the query parameters, there's no way for the parser to know that `?metadata_filter.a=123` means `a == 123` (int) or `a == "123"` (string). It just converted it to int.

![image](https://github.com/user-attachments/assets/84393dff-2e0e-4694-9ab7-d2bf19ce0d8f)

**Comment by creatorrr** [comment]
This isn't straightforward to fix so closing this for now
