### ISSUE TITLE
[Bug]: Codec route Chrome CORS issue on DEV

### ISSUE THREAD

**Issue by Vedantsahai18** [julep-ai/julep#810]
### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

**Comment by creatorrr** [comment]
It’s trying to connect to http://localhost/ but it should instead connect to https://dev.julep.ai/

**Comment by Vedantsahai18** [comment]
Yeah even I observed that but no clue why is it connecting to that url even after explicitly the defining the url.

**Comment by Vedantsahai18** [comment]
Apparently it is working on all browser except for Chrome.

**Comment by Vedantsahai18** [comment]
Change setting from cluster level to browser level in the codec setup.
