### ISSUE TITLE
[Bug]: execute_integration doesn't work correctly with browserbase if you use `DEMO_PROJECT_ID`

### ISSUE THREAD

**Issue by creatorrr** [julep-ai/julep#857]
### 📜 Description

worker-1                    | ERROR:temporalio.activity:Error in execute_integration: 'BrowserbaseSetup' object has no attribute 'browserbase_project_id' ({'activity_id': '3', 'activity_type': 'execute_integration', 'attempt': 1, 'namespace': 'default', 'task_queue': 'julep-task-queue', 'workflow_id': '2b59ea92-be25-46a5-94d8-9e99d9eae824', 'workflow_run_id': '4c10e891-1ca6-4d62-99c6-0d8e78bcd60d', 'workflow_type': 'TaskExecutionWorkflow'})

### 👀 Have you searched previous issues to see if this has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Vedantsahai18** [comment]
Created a PR for the same and have fixed it. Should be working now.
