### ISSUE TITLE
[Bug]: Getting UnprocessableEntityError on running python quick start snippet

### ISSUE THREAD

**Issue by Dream-gamer** [julep-ai/julep#872]
### 📜 Description

On running the code from python quick start section of readme, I am getting the error
 _UnprocessableEntityError: Error code: 422 - {'errors': ['Field required'], 'offending_input': {'name': 'research_wikipedia', 'integration': {'provider': 'wikipedia', 'method': 'search'}}, 'location': ['tools', 0, 'type']}_

### 👟 Reproduction steps

Steps to reproduce:
1. Copy the python quick start code from https://github.com/julep-ai/julep?tab=readme-ov-file#python-quick-start- in colab
2. Insert the julep api key and run the cell, you will encounter this error

### 👀 Have you searched previous issues to see if this has been raised before?

- [X] I checked and didn't find similar issue

**Comment by HamadaSalhab** [comment]
@Dream-gamer  @patcher9  Thanks for reporting this issue. I've just merged #875 that fixes it. You can copy the same block from the README, it should work. 

If you're interested about what was wrong:

Previously we allowed defining tools without the `type` attribute as it was inferred from the tool spec itself. However, now we are requiring the `type` attribute to be present in the tool definition. So for the example in the README, changing the `research_wikipedia` tool definition to this will fix the error you guys got.

```
tools:
  - name: research_wikipedia
    type: integration # <--- Added this
    integration:
      provider: wikipedia
      method: search
```
