### ISSUE TITLE
[Bug]: trip planner timeout

### ISSUE THREAD

**Issue by brandonopened** [julep-ai/julep#964]
### 📜 Description

Trying to use the trip planner agent and keep getting this error; i've entered julep openweather and brave API key's as export SERVICE_API_KEY=<apikey>'s 

perhaps the service is just down? Im using the cookbook code locally and the python program. 

### 👀 Have you searched previous issues to see if this has been raised before?

- [X] I checked and didn't find similar issue

**Comment by creatorrr** [comment]
cc/ @HamadaSalhab @Vedantsahai18

**Comment by HamadaSalhab** [comment]
Hello @brandonopened! Thanks for reporting this issue. Could you please provide some more details about the error you're getting?

**Comment by Vedantsahai18** [comment]
Hey @brandonopened,

I hope your bug is resolved  by now . We did test it out from our end and everything looks fine. In case the bug still persist, you can reopen this issue again or create a new one.

Cheers!
